# Ruta del cliente Minecraft respecto al launcher
game.path=../Minecraft


# Archivos del runtime Java
java.path=C:\Program Files\Eclipse Adoptium\jdk-25.0.3.9-hotspot\bin\java.exe


# Directorios principales del juego
versions.path=versions
libraries.path=libraries
assets.path=assets
mods.path=mods
config.path=config.json
minecraft.version=1.21.1

# Servidor de actualización
server.config=http://192.168.100.5:59381/server.json


# Opciones
enable.verify=false
delete_unauthorized=true