game.path=../Minecraft
java.path=runtime/java-runtime-delta/windows/java-runtime-delta/bin/java.exe
versions.path=versions
libraries.path=libraries
assets.path=assets
mods.path=mods
config.path=config.json
server.config=http://192.168.100.5:59381/server.json
verify.enabled=true
delete_unauthorized=true