# Ruta del cliente Minecraft respecto al launcher
game.path=../Minecraft


# Archivos del runtime Java
java.path=runtime/java-runtime-delta/windows/java-runtime-delta/bin/java.exe


# Directorios principales del juego
versions.path=versions
libraries.path=libraries
assets.path=assets
mods.path=mods
config.path=config.json
minecraft.version=versionloaded.json

# Servidor de actualización
server.config=http://192.168.100.5:59381/server.json


# Opciones
enable.verify=false
delete_unauthorized=true